### ISSUE TITLE
Tableau R Integration Error 

### ISSUE THREAD

**Issue by Prudha** [keberwein/Data_Science_Riot#1]
I am trying to run an R script from Tableau  and when passing the same, I get an error stating 
Error in x[1L:after] : only 0's may be mixed with negative subscripts
Can somebody please suggest me how to go about this error.

Thanks,

**Comment by keberwein** [comment]
That's R subsetting error. I am unable to replicate it. Are you using the data and Tableau workbook from this repository or something else?

**Comment by Prudha** [comment]
I am using the R code and your worksheets to build a duplicate dash board
for my reference using your resources.
while I didn't have any error opening your code and running your tableau
worksheet, I am getting error when I try to build the similar one using the
sample store data from tableau 10.
Can you please send me the workbook that has been  used to build your
Tableau Wordbook for forecasting the superstore sales?
I really appreciate your help, looking forward for your suggestions.
Thanks,
Prudha

*Prudha Pallavi Pentapati*
Ph: +1-702-750-7077

**Comment by keberwein** [comment]
It's here. Just click on the workbook. It will tell you it's "raw," but if you click on the download button above that, you'll be able to get it. You can download the .csv that was the exact data set I used as well--Tableau sometimes changes the "Super Store" data set, so I took a reproducible snapshot in case that were to happen.

**Comment by Prudha** [comment]
Hi
I am still getting the same error.
I don't know where I am doing wrong.
I don't understand what is a sub setting error.
Could please help me resolve the issue.

Thanks,
Prudha
