### ISSUE TITLE
Can't return unlimited n 

### ISSUE THREAD

**Issue by vicholec** [keberwein/Data_Science_Riot#2]
Hi! I am trying out your SuperTuesday sentiment analysis code in R. 

I am getting the following Warning Message in my Twitter search: 

> tweets_iccms17 <- searchTwitter('#iccms17 since:2017-11-01 until:2017-11-28', n=500)
Warning message:
In doRppAPICall("search/tweets", n, params = params, retryOnRateLimit = retryOnRateLimit,  :
  500 tweets were requested but the API can only return 5

Any idea on how to remedy this? Thank you!

**Comment by keberwein** [comment]
Sounds like it's not seeing a recognized Twitter API key. I've got my keys as "xxxxxx" in the code example, just to keep them private. If I remember correctly, you have to go to Twitter and "create an application." Check out Getting Started section of the `twitteR` package. https://github.com/geoffjentry/twitteR

Here's the Twitter Developer portal: https://developer.twitter.com/

**Comment by vicholec** [comment]
Hm, I did create an app for this and pasted all the relevant keys and secrets. Maybe I have to add the DM authorization...

**Comment by vicholec** [comment]
After adding that permission, it hasn't changed much... there must be something I am missing in the original twitteR. I will check it out, thanks! 

> ## Grab latest tweets
> tweets_iccms17 <- searchTwitter('iccms17', n=30000, since = '2017-11-01')
Warning message:
In doRppAPICall("search/tweets", n, params = params, retryOnRateLimit = retryOnRateLimit,  :
  30000 tweets were requested but the API can only return 8

**Comment by keberwein** [comment]
Maybe this helps? https://stackoverflow.com/questions/39992266/error-n-tweets-were-requested-but-the-api-can-only-return-0

**Comment by vicholec** [comment]
Thanks for your help! I am going to see how I can change that... Without having to connect a database!
